<a href="https://colab.research.google.com/github/Veena9977/Practice2/blob/main/Artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import pandas as pd


In [113]:
#Read the data
data = pd.read_csv('/content/mobile_price_classification.csv')

In [114]:
#Display the contents in first five rows.
data.head()

battery_power  bluetooth  clock_speed  dual_sim  front_cam  4G  int_memory  \
0            842          0          2.2         0          1   0           7   
1           1021          1          0.5         1          0   1          53   
2            563          1          0.5         1          2   1          41   
3            615          1          2.5         0          0   0          10   
4           1821          1          1.2         0         13   1          44   

   m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0    0.6        188        2  ...         20       756  2549     9     7   
1    0.7        136        3  ...        905      1988  2631    17     3   
2    0.9        145        5  ...       1263      1716  2603    11     2   
3    0.8        131        6  ...       1216      1786  2769    16     8   
4    0.6        141        2  ...       1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [115]:
#Dispaly the information about variables.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   battery_power   2000 non-null   int64  
 1   bluetooth       2000 non-null   int64  
 2   clock_speed     2000 non-null   float64
 3   dual_sim        2000 non-null   int64  
 4   front_cam       2000 non-null   int64  
 5   4G              2000 non-null   int64  
 6   int_memory      2000 non-null   int64  
 7   m_dep           2000 non-null   float64
 8   mobile_wt       2000 non-null   int64  
 9   n_cores         2000 non-null   int64  
 10  primary_camera  2000 non-null   int64  
 11  px_height       2000 non-null   int64  
 12  px_width        2000 non-null   int64  
 13  ram             2000 non-null   int64  
 14  sc_h            2000 non-null   int64  
 15  sc_w            2000 non-null   int64  
 16  talk_time       2000 non-null   int64  
 17  three_g         2000 non-null   i

In [116]:
#Chack for missing values
data.isna().sum()

battery_power     0
bluetooth         0
clock_speed       0
dual_sim          0
front_cam         0
4G                0
int_memory        0
m_dep             0
mobile_wt         0
n_cores           0
primary_camera    0
px_height         0
px_width          0
ram               0
sc_h              0
sc_w              0
talk_time         0
three_g           0
touch_screen      0
wifi              0
price_range       0
dtype: int64

In [117]:
pip install tensorflow keras-tuner

In [118]:
#Drop the target variable
X = data.drop('price_range',axis = 1)
y = data['price_range']

In [119]:
X.shape

(2000, 20)

In [120]:
## Convert to a numpy array
X = X.values
y = y.values

In [121]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state = 42,stratify=y)

In [122]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [123]:
#Scale the data
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [124]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import keras_tuner as kt


In [125]:
#Create a sequential model and adding the input layer and hidden layer.
model = Sequential()
model.add(Dense(64, input_dim=20, activation='relu'))  # input_dim=20 for 20 features
model.add(Dense(1, activation='sigmoid')) #Adding output layer to one neuron

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [126]:
#Compile the model
model.compile(loss = 'binary_crossentropy',optimizer = 'adam', metrics = ['accuracy'])

In [127]:
#Train the model
model.fit(X_train, y_train, batch_size=10, epochs=100, verbose=0)

In [128]:
#Predicting the test set results
y_pred = model.predict(X_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [149]:
# Convert probabilities to binary labels (0 or 1)
y_pred = (y_pred > 0.5).astype(int)

In [150]:
#Calculate accuracy score and evaluate the model.
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.47

In [131]:
#Making confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[ 90  10   0   0]
 [  2  98   0   0]
 [  0 100   0   0]
 [  0 100   0   0]]


In [132]:
#Display the classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred,zero_division=0))

              precision    recall  f1-score   support

           0       0.98      0.90      0.94       100
           1       0.32      0.98      0.48       100
           2       0.00      0.00      0.00       100
           3       0.00      0.00      0.00       100

    accuracy                           0.47       400
   macro avg       0.32      0.47      0.35       400
weighted avg       0.32      0.47      0.35       400



In [133]:
#Dispaly the model summary
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                     │ (None, 64)                  │           1,344 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,229 (16.52 KB)

 Trainable params: 1,409 (5.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,820 (11.02 KB)

In [134]:
#Create a function to build the ANN model
def build_model(hp):
  model = Sequential()

  model.add(Dense(hp.Int('units',min_value=16,max_value=128,step=16),activation='relu'))

  for i in range(hp.Int('num_layers',1,3)):
    model.add(Dense(hp.Int(f'units_{i}',min_value=16,max_value=128,step=16),activation='relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(
      optimizer = tf.keras.optimizers.get({
          'class_name': hp.Choice('optimizer',values=['adam','rmsprop','sgd']),
          'config' : {'learning_rate':hp.Float('learning_rate',min_value=1e-4,max_value=1e-2,sampling= 'log')}
      }),
      loss = 'binary_crossentropy',
      metrics = ['accuracy']
    )
  return model

In [135]:
# Create the tuner instance
tuner = kt.RandomSearch(
    build_model,
    objective = 'val_accuracy',
    max_trials = 5
)

Reloading Tuner from ./untitled_project/tuner0.json


In [136]:
# Now run the hyperparameter search
tuner.search(
    X_train,y_train,
    epochs =20,
    validation_split = 0.2,
    verbose = 1
)

In [137]:
# Get the best hyperparameters from the tuner and print the value of each hyperparameter
best_hps = tuner.get_best_hyperparameters(1)[0]
print('Units in 1st layer',best_hps.get('units'))
print('No of layers',best_hps.get('num_layers'))
for i in range(best_hps.get('num_layers')):
  print(f"units in layer {i+1}:{best_hps.get(f'units_{i}')}")
print('optimizer :',best_hps.get('optimizer'))
print('Learning rate :',best_hps.get('learning_rate'))


Units in 1st layer 64
No of layers 3
units in layer 1:16
units in layer 2:112
units in layer 3:48
optimizer : adam
Learning rate : 0.004495641842459814


In [138]:
from tensorflow.keras.layers import Dropout
from tensorflow.keras.regularizers import l2

In [139]:
# Define a function to build the ANN model with dropout and regularization tuning
def build_model(hp):
    model = Sequential()

    # First hidden layer with L2 regularization and dropout
    model.add(Dense(
        units=hp.Int('units', min_value=32, max_value=128, step=32),
        activation='relu',
        kernel_regularizer=l2(hp.Float('l2_regularizer', min_value=1e-5, max_value=1e-2, sampling='log')),
    ))
    model.add(Dropout(hp.Float('dropout_rate', min_value=0.2, max_value=0.5, step=0.1)))

    # Output layer
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [140]:
# Create the tuner instance
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='keras_tuner',
    project_name='tune_dropout_regularization'
)

Reloading Tuner from keras_tuner/tune_dropout_regularization/tuner0.json


In [145]:
# Now run the hyperparameter search
tuner.search(
    X_train, y_train,
    epochs=20,
    validation_split=0.2,
    verbose=1
)

In [146]:
# Get the best hyperparameters from the tuner and print the value of each hyperparameter
best_hps = tuner.get_best_hyperparameters(1)[0]
print('Units in 1st layer',best_hps.get('units'))
print('L2 Regularizer :',best_hps.get('l2_regularizer'))
print("Dropout rate :", best_hps.get('dropout_rate'))

Units in 1st layer 64
L2 Regularizer : 0.0002049915877565318
Dropout rate : 0.2
